"""initial FileJournal and AuditLog schema

Revision ID: 147ff406b539
Revises: 
Create Date: 2025-12-04 12:25:24.579927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147ff406b539'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('book_id', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('new_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint("agent_id != ''", name='ck_agent_not_empty'),
    sa.CheckConstraint("agent_id != 'system'", name='ck_agent_not_system'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_book_path_user', 'audit_log', ['book_id', 'path', 'user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_agent_id'), 'audit_log', ['agent_id'], unique=False)
    op.create_index(op.f('ix_audit_log_book_id'), 'audit_log', ['book_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('file_journal',
    sa.Column('book_id', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('last_written_at', sa.DateTime(), nullable=False),
    sa.Column('storage_backend', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('book_id', 'path', 'user_id')
    )
    op.create_index('ix_file_journal_book_path', 'file_journal', ['book_id', 'path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_journal_book_path', table_name='file_journal')
    op.drop_table('file_journal')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_book_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_agent_id'), table_name='audit_log')
    op.drop_index('ix_audit_book_path_user', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
