"""use timezone aware timestamps

Revision ID: 853c7e2d6e2a
Revises: 147ff406b539
Create Date: 2025-12-05 00:19:44.307900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '853c7e2d6e2a'
down_revision: Union[str, Sequence[str], None] = '147ff406b539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manifest_snapshot',
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('manifest_hash')
    )
    op.create_index('ix_manifest_book_created', 'manifest_snapshot', ['book_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_manifest_snapshot_book_id'), 'manifest_snapshot', ['book_id'], unique=False)
    op.alter_column('audit_log', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('file_journal', 'last_written_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_journal', 'last_written_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('audit_log', 'timestamp',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_manifest_snapshot_book_id'), table_name='manifest_snapshot')
    op.drop_index('ix_manifest_book_created', table_name='manifest_snapshot')
    op.drop_table('manifest_snapshot')
    # ### end Alembic commands ###
